language: php

php:
  - 7
  
global:
  - CI=true
  - CI_ENV=testing

# Recommended by Travis support
sudo: required
dist: precise

env:
  - DB_GROUP=mysqli
  - DB_GROUP=postgres

script:
  - php vendor/bin/phpunit -v

services:
  - mysql
  - postgresql

before_install:
  - if [ $DB_GROUP = 'mysqli' ]; then mysql -e "create database IF NOT EXISTS satoripop;" -uroot; fi
  - if [ $DB_GROUP = 'postgres' ]; then psql -c 'create database satoripop;' -U postgres; fi

before_script:
  - composer install
  
after_success:
  - travis_retry php vendor/bin/coveralls
